[package]
name = "webhook"
version = "0.1.0"
authors = ["uma <blog3170@gmail.com>"]

[dependencies]
rocket = "0.3.12"
rocket_codegen = "0.3.12"
rocket_contrib = "0.3.12"
line-messaging-api-rocket = { git = "https://github.com/uma0317/line-messaging-api-rocket"}